const seedProducts = [
  {
    name: "Almond Protein Cookie",
    slug: "almond-protein-cookie",
    category: "cookie",
    image: "/virteez/Almond cookie box.jpeg",
    images: [
      "/virteez/Almond cookie box.jpeg",
      "/virteez/Almond cookies in plate.jpeg",
      "/virteez/Almond cookies in plate along with box.jpeg",
    ],
    rating: 4.8,
    reviews: 34,
    price: 299,
    originalPrice: 399,
    discount: "25% OFF",
    weight: "200g (Pack of 6)",
    description: "Crunchy almond protein cookies loaded with real almonds and whey protein.",
    benefits: ["10g Protein per cookie", "No Added Sugar", "Real Almonds", "High Fibre"],
    ingredients: "Whey Protein Concentrate, Almonds, Oat Flour, Coconut Oil, Stevia.",
    nutritionHighlights: ["10g Protein", "5g Fibre", "0g Added Sugar", "150 Kcal"],
  },
  {
    name: "Blueberry Protein Cookie",
    slug: "blueberry-protein-cookie",
    category: "cookie",
    image: "/virteez/Blueberry cookie box front side.jpeg",
    images: ["/virteez/Blueberry cookie box front side.jpeg", "/virteez/Blueberry cookies.jpeg"],
    rating: 4.9,
    reviews: 42,
    price: 299,
    originalPrice: 399,
    discount: "25% OFF",
    weight: "200g (Pack of 6)",
    description: "Bursting with real blueberries and packed with high-quality whey protein.",
    benefits: ["10g Protein per cookie", "Real Blueberries", "Antioxidant-rich", "No Added Sugar"],
    ingredients: "Whey Protein Concentrate, Blueberries, Oat Flour, Coconut Oil, Stevia.",
    nutritionHighlights: ["10g Protein", "4g Fibre", "0g Added Sugar", "145 Kcal"],
  },
  {
    name: "Cashew Protein Cookie",
    slug: "cashew-protein-cookie",
    category: "cookie",
    image: "/virteez/Cashew cookie box.jpeg",
    images: ["/virteez/Cashew cookie box.jpeg"],
    rating: 4.7,
    reviews: 28,
    price: 319,
    originalPrice: 429,
    discount: "25% OFF",
    weight: "200g (Pack of 6)",
    description: "Premium cashew-loaded protein cookies with a buttery crunch.",
    benefits: ["10g Protein per cookie", "Real Cashews"],
    ingredients: "Whey Protein Concentrate, Cashews, Oat Flour, Coconut Oil, Stevia.",
    nutritionHighlights: ["10g Protein", "4g Fibre", "160 Kcal"],
  },
  {
    name: "Coconut Protein Cookie",
    slug: "coconut-protein-cookie",
    category: "cookie",
    image: "/virteez/Coconut cookie box.jpeg",
    images: ["/virteez/Coconut cookie box.jpeg"],
    rating: 4.6,
    reviews: 22,
    price: 279,
    originalPrice: 379,
    discount: "26% OFF",
    weight: "200g (Pack of 6)",
    description: "Tropical coconut meets high-protein goodness.",
    benefits: ["10g Protein per cookie", "MCT from Coconut"],
    ingredients: "Whey Protein Concentrate, Coconut, Oat Flour, Coconut Oil, Stevia.",
    nutritionHighlights: ["10g Protein", "5g Fibre", "155 Kcal"],
  },
  {
    name: "Cranberry Protein Cookie",
    slug: "cranberry-protein-cookie",
    category: "cookie",
    image: "/virteez/Cranberry cookie box front side.jpeg",
    images: ["/virteez/Cranberry cookie box front side.jpeg"],
    rating: 4.7,
    reviews: 31,
    price: 299,
    originalPrice: 399,
    discount: "25% OFF",
    weight: "200g (Pack of 6)",
    description: "Tangy cranberry meets protein power.",
    benefits: ["10g Protein per cookie", "Real Cranberries"],
    ingredients: "Whey Protein Concentrate, Cranberries, Oat Flour, Coconut Oil, Stevia.",
    nutritionHighlights: ["10g Protein", "4g Fibre", "148 Kcal"],
  },
  {
    name: "Walnut Protein Cookie",
    slug: "walnut-protein-cookie",
    category: "cookie",
    image: "/virteez/Walnut cookie box.jpeg",
    images: ["/virteez/Walnut cookie box.jpeg"],
    rating: 4.8,
    reviews: 26,
    price: 329,
    originalPrice: 449,
    discount: "27% OFF",
    weight: "200g (Pack of 6)",
    description: "Omega-3 rich walnuts meet premium whey protein.",
    benefits: ["10g Protein per cookie", "Omega-3 Fatty Acids"],
    ingredients: "Whey Protein Concentrate, Walnuts, Oat Flour, Coconut Oil, Stevia.",
    nutritionHighlights: ["10g Protein", "5g Fibre", "162 Kcal"],
  },
  {
    name: "Assorted Cookie Box",
    slug: "assorted-cookie-box",
    category: "cookie",
    image: "/virteez/Assorted cookie box.jpeg",
    images: ["/virteez/Assorted cookie box.jpeg"],
    rating: 5,
    reviews: 58,
    price: 549,
    originalPrice: 749,
    discount: "27% OFF",
    weight: "400g (12 Cookies)",
    description: "Get all best-selling flavours in one box.",
    benefits: ["All Flavours Included", "Great Gift Option"],
    ingredients: "See individual flavours.",
    nutritionHighlights: ["10g Protein each", "12 Cookies"],
  },
  {
    name: "Protein Energy Bar",
    slug: "protein-energy-bar",
    category: "energy-bar",
    image: "/virteez/Energy bar with packaging.jpeg",
    images: ["/virteez/Energy bar with packaging.jpeg", "/virteez/Energy bar.jpeg"],
    rating: 4.9,
    reviews: 67,
    price: 149,
    originalPrice: 199,
    discount: "25% OFF",
    weight: "60g (Single Bar)",
    description: "A chewy protein bar packed with 21g protein.",
    benefits: ["21g Protein", "Pre/Post Workout"],
    ingredients: "Whey Isolate, Oats, Dark Chocolate, Nuts.",
    nutritionHighlights: ["21g Protein", "220 Kcal"],
  },
  {
    name: "Protein Energy Bar - Pack of 6",
    slug: "protein-energy-bar-pack-6",
    category: "energy-bar",
    image: "/virteez/Energy bar with packaging.jpeg",
    images: ["/virteez/Energy bar with packaging.jpeg"],
    rating: 4.9,
    reviews: 45,
    price: 749,
    originalPrice: 1194,
    discount: "37% OFF",
    weight: "360g (Pack of 6)",
    description: "Stock up with six bars for the week.",
    benefits: ["6 Bars Pack", "21g Protein Each"],
    ingredients: "Whey Isolate, Oats, Dark Chocolate, Nuts.",
    nutritionHighlights: ["21g Protein each", "6 Bars"],
  },
  {
    name: "Desert Date Protein Drops",
    slug: "desert-date-protein-drops",
    category: "desert-date",
    image: "/virteez/Desert dates drops.jpeg",
    images: ["/virteez/Desert dates drops.jpeg"],
    rating: 4.6,
    reviews: 21,
    price: 249,
    originalPrice: 349,
    discount: "29% OFF",
    weight: "150g",
    description: "Soft date drops blended with protein and nuts.",
    benefits: ["Natural Sweetness", "Protein Rich"],
    ingredients: "Dates, Whey Protein, Almonds, Cocoa.",
    nutritionHighlights: ["8g Protein", "No Refined Sugar"],
  },
];

module.exports = { seedProducts };
