const seedProducts = [
  {
    name: "Almond Vital Energy",
    slug: "almond-vital-energy",
    category: "cookies",
    image: "/virteez/Almond cookie box.jpeg",
    images: ["/virteez/Almond cookie box.jpeg", "/virteez/Almond cookies in plate.jpeg"],
    rating: 4.8,
    reviews: 36,
    price: 276,
    originalPrice: 276,
    discount: "Pack of 2",
    weight: "110 g (Pack of 2)",
    description: "Crunchy almond cookies offering protein, energy, and daily wellness.",
    benefits: ["Protein-rich", "Energy Support", "Daily Wellness"],
    ingredients: "Almonds, wholesome flour blend, natural sweeteners, and premium fats.",
    nutritionHighlights: ["110 g pack", "120 days shelf life", "Daily wellness snack"],
  },
  {
    name: "Coconut Pure Delights",
    slug: "coconut-pure-delights",
    category: "cookies",
    image: "/virteez/Coconut cookie box.jpeg",
    images: ["/virteez/Coconut cookie box.jpeg", "/virteez/Coconut cookies in plate.jpeg"],
    rating: 4.7,
    reviews: 29,
    price: 240,
    originalPrice: 240,
    discount: "Pack of 2",
    weight: "110 g (Pack of 2)",
    description: "Light, naturally sweet coconut cookies for wholesome energy.",
    benefits: ["Naturally Sweet", "Wholesome Energy", "Clean Label"],
    ingredients: "Coconut, wholesome flour blend, natural sweeteners, and premium fats.",
    nutritionHighlights: ["110 g pack", "120 days shelf life", "Clean label"],
  },
  {
    name: "Walnut Brain Harmony",
    slug: "walnut-brain-harmony",
    category: "cookies",
    image: "/virteez/Walnut cookie box.jpeg",
    images: ["/virteez/Walnut cookie box.jpeg", "/virteez/Walnut cookies in plate.jpeg"],
    rating: 4.8,
    reviews: 31,
    price: 288,
    originalPrice: 288,
    discount: "Pack of 2",
    weight: "110 g (Pack of 2)",
    description: "Crunchy walnut cookies crafted to support focus and brain wellness.",
    benefits: ["Brain Wellness", "Focus Support", "Crunchy Texture"],
    ingredients: "Walnuts, wholesome flour blend, natural sweeteners, and premium fats.",
    nutritionHighlights: ["110 g pack", "120 days shelf life", "Focus support"],
  },
  {
    name: "Cashew Cardio Balance",
    slug: "cashew-cardio-balance",
    category: "cookies",
    image: "/virteez/Cashew cookie box.jpeg",
    images: ["/virteez/Cashew cookie box.jpeg", "/virteez/Cashew cookies in plate along with box.jpeg"],
    rating: 4.7,
    reviews: 27,
    price: 288,
    originalPrice: 288,
    discount: "Pack of 2",
    weight: "110 g (Pack of 2)",
    description: "Creamy cashew cookies designed for heart-friendly nourishment and energy.",
    benefits: ["Heart Friendly", "Energy Support", "Creamy Crunch"],
    ingredients: "Cashews, wholesome flour blend, natural sweeteners, and premium fats.",
    nutritionHighlights: ["110 g pack", "120 days shelf life", "Heart-friendly"],
  },
  {
    name: "Blueberry Infused Cookies",
    slug: "blueberry-infused-cookies",
    category: "infused-cookie",
    image: "/virteez/Blueberry cookie box front side.jpeg",
    images: ["/virteez/Blueberry cookie box front side.jpeg", "/virteez/Blueberry cookies.jpeg"],
    rating: 4.9,
    reviews: 44,
    price: 178,
    originalPrice: 178,
    discount: "Pack of 2",
    weight: "70 g (Pack of 2)",
    description: "Buttery cookies enriched with antioxidant-rich blueberries for a flavourful, wellness-friendly treat.",
    benefits: ["Antioxidant-rich", "Wellness-friendly", "Flavourful"],
    ingredients: "Blueberries, wholesome flour blend, natural sweeteners, and premium fats.",
    nutritionHighlights: ["70 g pack", "120 days shelf life", "2-pack"],
  },
  {
    name: "Cranberry Infused Cookies",
    slug: "cranberry-infused-cookies",
    category: "infused-cookie",
    image: "/virteez/Cranberry cookie box front side.jpeg",
    images: ["/virteez/Cranberry cookie box front side.jpeg"],
    rating: 4.8,
    reviews: 39,
    price: 178,
    originalPrice: 178,
    discount: "Pack of 2",
    weight: "70 g (Pack of 2)",
    description: "Sweet-tart cranberry cookies packed with natural antioxidants and a crisp, indulgent bite.",
    benefits: ["Antioxidant-rich", "Sweet-tart", "Crisp Bite"],
    ingredients: "Cranberries, wholesome flour blend, natural sweeteners, and premium fats.",
    nutritionHighlights: ["70 g pack", "120 days shelf life", "2-pack"],
  },
  {
    name: "Desert Dates Drops",
    slug: "desert-dates-drops",
    category: "infused-cookie",
    image: "/virteez/Desert dates drops.jpeg",
    images: ["/virteez/Desert dates drops.jpeg"],
    rating: 4.5,
    reviews: 18,
    price: 0,
    originalPrice: 0,
    discount: "Upcoming",
    weight: "70 g (Upcoming)",
    description: "Soft, naturally sweet date cookies for instant energy and wholesome delight.",
    benefits: ["Upcoming", "Natural Sweetness", "Instant Energy"],
    ingredients: "Dates, wholesome flour blend, and natural sweeteners.",
    nutritionHighlights: ["70 g pack", "120 days shelf life", "Upcoming"],
    isActive: false,
    stock: 0,
  },
  {
    name: "Energy Bar",
    slug: "energy-bar",
    category: "energy-on-the-go",
    image: "/virteez/Energy bar with packaging.jpeg",
    images: ["/virteez/Energy bar with packaging.jpeg", "/virteez/Energy bar.jpeg"],
    rating: 4.9,
    reviews: 71,
    price: 158,
    originalPrice: 158,
    discount: "Pack of 2",
    weight: "40 g (Pack of 2)",
    description: "Nut and seed bar designed to boost stamina and keep you going.",
    benefits: ["Stamina Boost", "Nut & Seed", "On-the-go Energy"],
    ingredients: "Nuts, seeds, wholesome binders, and natural sweeteners.",
    nutritionHighlights: ["40 g pack", "6 months shelf life", "2-pack"],
  },
  {
    name: "Energy Booster",
    slug: "energy-booster",
    category: "energy-on-the-go",
    image: "/virteez/Energy bar closeup.jpeg",
    images: ["/virteez/Energy bar closeup.jpeg"],
    rating: 4.5,
    reviews: 13,
    price: 0,
    originalPrice: 0,
    discount: "Upcoming",
    weight: "40 g (Upcoming)",
    description: "A compact superfoods, nuts, and seeds to enhance vitality and endurance.",
    benefits: ["Upcoming", "Vitality Support", "Endurance"],
    ingredients: "Superfoods, nuts, seeds, and natural binders.",
    nutritionHighlights: ["40 g pack", "6 months shelf life", "Upcoming"],
    isActive: false,
    stock: 0,
  },
  {
    name: "Classic Masala Makhana",
    slug: "classic-masala-makhana",
    category: "savory-snacks",
    image: "/virteez/Assorted cookie box.jpeg",
    images: ["/virteez/Assorted cookie box.jpeg"],
    rating: 4.6,
    reviews: 24,
    price: 60,
    originalPrice: 60,
    discount: "PET Jar",
    weight: "20 g",
    description: "Light, air-crisped makhana seasoned to perfection for a clean, elegant crunch.",
    benefits: ["Light Crunch", "Clean Snack", "Vrat Friendly"],
    ingredients: "Makhana, spices, rock salt, and premium seasoning.",
    nutritionHighlights: ["20 g jar", "120 days shelf life", "Classic masala"],
  },
  {
    name: "Minty Makhana",
    slug: "minty-makhana",
    category: "savory-snacks",
    image: "/virteez/Blueberry cookies.jpeg",
    images: ["/virteez/Blueberry cookies.jpeg"],
    rating: 4.5,
    reviews: 19,
    price: 60,
    originalPrice: 60,
    discount: "PET Jar",
    weight: "20 g",
    description: "Cooling mint-flavoured makhana for a refreshing, savoury crunch.",
    benefits: ["Refreshing", "Clean Crunch", "Vrat Friendly"],
    ingredients: "Makhana, mint seasoning, rock salt, and premium seasoning.",
    nutritionHighlights: ["20 g jar", "120 days shelf life", "Mint flavoured"],
  },
  {
    name: "Falahaari Crunchy Bites",
    slug: "falahaari-crunchy-bites",
    category: "savory-snacks",
    image: "/virteez/Almond cookies in plate along with box.jpeg",
    images: ["/virteez/Almond cookies in plate along with box.jpeg"],
    rating: 4.6,
    reviews: 21,
    price: 90,
    originalPrice: 90,
    discount: "PET Jar",
    weight: "90 g",
    description: "Savory, mathri-style bites made with wholesome barnyard millet for a crunchy, guilt-free snack.",
    benefits: ["Wholesome Crunch", "Barnyard Millet", "Guilt-free"],
    ingredients: "Barnyard millet, spices, premium fats, and seasoning.",
    nutritionHighlights: ["90 g jar", "120 days shelf life", "Falahaari snack"],
  },
  {
    name: "Falahaari Chips",
    slug: "falahaari-chips",
    category: "savory-snacks",
    image: "/virteez/Cashew cookies in plate along with box.jpeg",
    images: ["/virteez/Cashew cookies in plate along with box.jpeg"],
    rating: 4.4,
    reviews: 16,
    price: 90,
    originalPrice: 90,
    discount: "PET Jar",
    weight: "90 g",
    description: "Light falahaari chips crafted for a crisp, savoury snack break.",
    benefits: ["Crisp Snack", "Falahaari", "Light Bite"],
    ingredients: "Millet blend, spices, and premium seasoning.",
    nutritionHighlights: ["90 g jar", "120 days shelf life", "Falahaari chips"],
  },
  {
    name: "Instant Sama Upma",
    slug: "instant-sama-upma",
    category: "wholesome-delights",
    image: "/virteez/Energy bar.jpeg",
    images: ["/virteez/Energy bar.jpeg"],
    rating: 4.7,
    reviews: 33,
    price: 69,
    originalPrice: 69,
    discount: "Pouch",
    weight: "40 g",
    description: "Quick-cooking wholesome sama (barnyard millet) mix for nutritious, convenient meals.",
    benefits: ["Quick Meal", "Wholesome", "Vrat Friendly"],
    ingredients: "Barnyard millet (sama), spices, herbs, and seasoning.",
    nutritionHighlights: ["40 g pouch", "120 days shelf life", "Instant meal"],
  },
];

module.exports = { seedProducts };
